#!/usr/bin/env bash
# Install nginx in the server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start