#!/usr/bin/env bash
# Configure server to redirect

string='server_name _;\n\trewrite ^redirect_me/$ https://www.youtube.com
/watch?v=QH2-TGUlwu4;'


sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sed -i "s/server_name\ _;/$string/g" /etc/nginx/sites-available/default
sudo service nginx start