#!/usr/bin/env bash
# Configure server to redirect

string="/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"

sudo apt update
sudp apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i $string $file
sudo service nginx restart