#!/usr/bin/env bash
# Configures a server and add a http header

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
search="listen 80 default_server;"
new_line="add_header X-Served-By $HOSTNAME;"
file="/etc/nginx/sites-available/default"
sudo sed -i "/$search/a$new_line" $file
sudo service nginx restart
