#!/usr/bin/env bash
# Bash script to install and configure HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
path="/etc/haproxy/haproxy.cfg"
text="frontend myfrontend
        bind :80
        mode http
        default_backend myservers

backend myservers
        balance roundrobin
        server 3309-web-01 34.138.152.200:80 check
        server 3309-web-02 3.85.201.247:80 check"
echo "$text" | sudo tee -a $path >/dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy >/dev/null
sudo service haproxy start
