#!/usr/bin/env bash
# Bash script to install and configure HAProxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5 -y
sudo apt-get install -y haproxy=2.5.\*
path="/etc/haproxy/haproxy.cfg"
text="frontend myfrontend
        bind :80
        default_backend myservers

backend myservers
        balance roundrobin
        server 3309-web-01 34.138.152.200:80
        server 3309-web-02 3.85.201.247:80"
echo "$text" | sudo tee -a $path >/dev/null
